TETRATAGGER = "tetra"
TD_SR = "td-sr"
BU_SR = "bu-sr"
BERT = "bert"
BERTCRF = "bert+crf"
BERTLSTM = "bert+lstm"

BAQ = "Basque"
FRE = "French"
GER = "German"
HEB = "Hebrew"
HUN = "Hungarian"
KOR = "Korean"
POL = "Polish"
SWE = "Swedish"
ENG = "English"
LANG = [BAQ, FRE, GER, HEB, HUN, KOR, POL, SWE, ENG]