name: partial
channels:
  - pytorch
  - huggingface
  - nvidia
  - defaults
dependencies:
  - python
  - pip
  - pytorch=2.3.0
  - yaml
  - pip:
      - nltk
      - tqdm
      - numpy
      - scikit-learn
      - bitsandbytes
      - huggingface-hub
      - tensorboard
      - transformers==4.40.1
